### ISSUE TITLE
Hardcoded key in the api

### ISSUE THREAD

**Issue by tommytcchan** [djtech42/YikYakTerminal#13]
Hey I was looking at the code and there was mentioning of the key = "F7CAFA2F-FE67-4E03-A090-AC7FFF010729"

Is this key always the same? Did you find it from the decoded apk?

**Comment by djtech42** [comment]
The key was extracted from the decoded iOS version a while ago. The key changed at some point, so it doesn't stay the same all the time.

**Comment by pmauldin** [comment]
I decompiled the latest (2.8.2) android version apk and can't find the key anywhere. I'm looking for it because if they change it later it could break the app I'm building, so I'd like to know how to find it again. Do you have any advice as to where I can find this key? Project structure, variable name, etc. Thanks!
